-- CRIANDO O BANCO DE DADOS
create database teste;
-- CRIANDO A TABELA ESTADOS
create table ESTADOS(
CODIGO INT auto_increment primary key ,
NOME VARCHAR(50)
);
-- CRIANDO TABELA CIDADES
create table CIDADES(
CODIGO INT auto_increment primary key,
NOME VARCHAR(50),
CODIGOESTADO INT 
);

ALTER TABLE CIDADES ADD CONSTRAINT FK_CIDADES
FOREIGN KEY (CODIGOESTADO) REFERENCES estados(CODIGO);


-- CRIANDO A TABELA OPERADORES
CREATE TABLE OPERADORES( 
CODIGO  INT auto_increment primary key,
NOME VARCHAR(50),
CODIGOESTADO INT 
);

ALTER TABLE OPERADORES ADD CONSTRAINT FK_OPERADORES
FOREIGN KEY (CODIGOESTADO) REFERENCES estados(CODIGO);

-- CRIANDO A TABELA LIGACOES
CREATE TABLE LIGACOES( 
NUMEROCLIENTE  VARCHAR(50),
DATAHORA datetime, 
CODIGODOOPERADOR INT
);

ALTER TABLE LIGACOES ADD CONSTRAINT FK_LIGACOES
FOREIGN KEY (CODIGODOOPERADOR) REFERENCES OPERADORES(CODIGO);

